[CommonVariables]
CommonVar1 = "foo"

[[repositories]]
Name = "lib-1"
HumanName = "Library 1"
URL = "http://{{ .Variables.GoPackage }}"
Templates = ["license", "lib"]
RunCmds = [["touch", "cmd-file"]]

    [repositories.Variables]
        Licence = "MIT"
        Author = "Robert Laszczak"
        GoPackage = "github.com/roblaszczak/lib-1"
        TemplatedVariable = "{{ .Name }}_foo"

[[repositories]]
Name = "service-1"
HumanName = "Service 1"
URL = "http://github.com/roblaszczak/service-1"
Templates = ["license", "service"]

    [repositories.Variables]
        Licence = "BSD"
        Author = "Three Dots Labs"
        GoPackage = "github.com/roblaszczak/lib-1"
        RunCommandDirectory = "cmd/app"
